// OT-207: two fixed Ed25519 vectors from pinned libsodium 1.0.22
// libsodium/test/default/sign.c, test_data[0] and test_data[1].
// These are RFC 8032 section 7.1 TEST 1 and TEST 2; expected bytes are
// copied from those retained upstream fixtures, never generated by this test.
#include <array>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sodium.h>

#define CHECK(x) do { if (!(x)) { std::fprintf(stderr, "failed line %d\n", __LINE__); std::exit(1); } } while (0)

struct Vector { const char* seed; const char* public_key; const char* signature; const char* message; };
static constexpr Vector vectors[] = {
    {"9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
     "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
     "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155"
     "5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b", ""},
    {"4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
     "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
     "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da"
     "085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00", "72"},
};

template<std::size_t N> std::array<unsigned char, N> unhex(const char* value) {
    CHECK(std::strlen(value) == N * 2);
    std::array<unsigned char, N> result{};
    for (std::size_t i = 0; i < N; ++i) {
        unsigned byte = 0;
        CHECK(std::sscanf(value + i * 2, "%2x", &byte) == 1);
        result[i] = static_cast<unsigned char>(byte);
    }
    return result;
}

int main() {
    unsigned groups = 0;
    for (const auto& v : vectors) {
        const auto seed = unhex<32>(v.seed);
        const auto expected_public = unhex<32>(v.public_key);
        const auto expected_signature = unhex<64>(v.signature);
        std::array<unsigned char, 32> public_key{};
        std::array<unsigned char, 64> secret_key{};
        // A nonnull byte also represents the zero-length message.
        std::array<unsigned char, 1> message{0x72};
        const auto length = std::strlen(v.message) / 2;
        CHECK(length <= message.size());
        if (length) CHECK(message == unhex<1>(v.message));
        CHECK(crypto_sign_seed_keypair(public_key.data(), secret_key.data(), seed.data()) == 0);
        CHECK(public_key == expected_public);
        ++groups;

        std::array<unsigned char, 66> signature{};
        signature.fill(0xa5);
        unsigned long long signature_length = 0;
        CHECK(crypto_sign_detached(signature.data() + 1, &signature_length, message.data(),
                                   length, secret_key.data()) == 0);
        CHECK(signature_length == 64 && signature.front() == 0xa5 && signature.back() == 0xa5);
        CHECK(std::memcmp(signature.data() + 1, expected_signature.data(), 64) == 0);
        CHECK(crypto_sign_verify_detached(expected_signature.data(), message.data(), length,
                                          expected_public.data()) == 0);
        ++groups;

        auto bad_signature = expected_signature;
        bad_signature[0] ^= 1;
        const auto saved_signature = bad_signature;
        CHECK(crypto_sign_verify_detached(bad_signature.data(), message.data(), length,
                                          expected_public.data()) != 0);
        CHECK(bad_signature == saved_signature);
        ++groups;

        auto bad_message = message;
        bad_message[0] ^= 1;
        CHECK(crypto_sign_verify_detached(expected_signature.data(), bad_message.data(), 1,
                                          expected_public.data()) != 0);
        CHECK(bad_message[0] == static_cast<unsigned char>(message[0] ^ 1));
        ++groups;

        auto bad_public = expected_public;
        bad_public[0] ^= 1;
        const auto saved_public = bad_public;
        CHECK(crypto_sign_verify_detached(expected_signature.data(), message.data(), length,
                                          bad_public.data()) != 0);
        CHECK(bad_public == saved_public);
        ++groups;
        sodium_memzero(secret_key.data(), secret_key.size());
    }
    std::printf("PASS %u pinned Ed25519 known-answer and refusal groups\n", groups);
}
