// Generated by tools/region_selection_catalog.py. Saved selection only; TX disabled.
#pragma once
#include <array>
#include <cstdint>
namespace opentrail::companion {
struct RegionCatalogEntry { std::uint16_t id; const char* code; };
inline constexpr std::array<RegionCatalogEntry, 12> kRegionCatalog{{
    {1, "US915"},
    {2, "EU868"},
    {3, "AU915"},
    {4, "EU433"},
    {5, "CN470"},
    {6, "AS923-1"},
    {7, "AS923-2"},
    {8, "AS923-3"},
    {9, "AS923-4"},
    {10, "KR920"},
    {11, "IN865"},
    {12, "RU864"},
}};
[[nodiscard]] constexpr bool region_selection_supported(std::uint16_t id) {
    for (const auto& entry : kRegionCatalog) if (entry.id == id) return true;
    return false;
}
[[nodiscard]] constexpr const char* region_selection_label(std::uint16_t id) {
    for (const auto& entry : kRegionCatalog) if (entry.id == id) return entry.code;
    return nullptr;
}
} // namespace opentrail::companion
