// Generated by tools/region_selection_catalog.py. Saved selection only; TX disabled.
package io.github.nbjelanovic.otprotocol

data class RegionSelection(val id: Int, val code: String)

object RegionSelectionCatalog {
    val entries: List<RegionSelection> = listOf(
        RegionSelection(1, "US915"),
        RegionSelection(2, "EU868"),
        RegionSelection(3, "AU915"),
        RegionSelection(4, "EU433"),
        RegionSelection(5, "CN470"),
        RegionSelection(6, "AS923-1"),
        RegionSelection(7, "AS923-2"),
        RegionSelection(8, "AS923-3"),
        RegionSelection(9, "AS923-4"),
        RegionSelection(10, "KR920"),
        RegionSelection(11, "IN865"),
        RegionSelection(12, "RU864"),
    )
    fun find(id: Int): RegionSelection? = entries.singleOrNull { it.id == id }
}
