"""Generate matched saved-region catalogs; these grant no RF authority."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "protocol/REGION_SELECTION_CATALOG_V1.json"
CPP = ROOT / "firmware/components/companion/include/opentrail/companion_region_catalog.hpp"
KOTLIN = ROOT / "android/protocol/src/main/kotlin/io/github/nbjelanovic/otprotocol/RegionSelectionCatalog.kt"

def rendered():
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    if data.get("schema") != "OT-REGION-CATALOG/v1" or data.get("version") != 1:
        raise ValueError("catalog_version")
    entries = data["entries"]
    ids = [e["id"] for e in entries]
    codes = [e["code"] for e in entries]
    if not entries or ids != sorted(set(ids)) or len(codes) != len(set(codes)):
        raise ValueError("catalog_identity")
    for e in entries:
        if type(e["id"]) is not int or not 1 <= e["id"] <= 65535:
            raise ValueError("catalog_id")
        if not re.fullmatch(r"[A-Z][A-Z0-9-]{1,11}", e["code"]):
            raise ValueError("catalog_code")
        if e["transmit_validated"] is not False:
            raise ValueError("selection_does_not_grant_transmit")
    cpp = """// Generated by tools/region_selection_catalog.py. Saved selection only; TX disabled.
#pragma once
#include <array>
#include <cstdint>
namespace opentrail::companion {
struct RegionCatalogEntry { std::uint16_t id; const char* code; };
"""
    cpp += f"inline constexpr std::array<RegionCatalogEntry, {len(entries)}> kRegionCatalog{{{{\n"
    cpp += "".join(f'    {{{e["id"]}, "{e["code"]}"}},\n' for e in entries)
    cpp += """}};
[[nodiscard]] constexpr bool region_selection_supported(std::uint16_t id) {
    for (const auto& entry : kRegionCatalog) if (entry.id == id) return true;
    return false;
}
[[nodiscard]] constexpr const char* region_selection_label(std::uint16_t id) {
    for (const auto& entry : kRegionCatalog) if (entry.id == id) return entry.code;
    return nullptr;
}
} // namespace opentrail::companion
"""
    kotlin = """// Generated by tools/region_selection_catalog.py. Saved selection only; TX disabled.
package io.github.nbjelanovic.otprotocol

data class RegionSelection(val id: Int, val code: String)

object RegionSelectionCatalog {
    val entries: List<RegionSelection> = listOf(
"""
    kotlin += "".join(f'        RegionSelection({e["id"]}, "{e["code"]}"),\n' for e in entries)
    kotlin += """    )
    fun find(id: Int): RegionSelection? = entries.singleOrNull { it.id == id }
}
"""
    return {CPP: cpp, KOTLIN: kotlin}

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    for path, content in rendered().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
        elif not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"FAIL generated catalog differs: {path.relative_to(ROOT)}")
    print("PASS matched C++/Kotlin saved-region catalog; no TX authority")

if __name__ == "__main__":
    main()
